### ISSUE TITLE
Refactoring request: Hide ShoppingList Checkbox variables and functionality in additional class

### ISSUE THREAD

**Issue by Ecconia** [SadieDragon/TPR-Hints-Tool#89]
The ShoppingList GUI element can have two entirely different types of contents.
A text field for notes and a checklist for progress tracking.

It would be cleaner, to create a class for each of the two visual elements, as that allows easy switching between them. As simply the class instance for each of the gui thingies can be disposed of along with all variables, instead of manually resetting variables.

^This implies that the ShoppingList is reset and reused instead of recreated every time.

**Comment by SadieDragon** [comment]
To format later

Also; note that the checklists are basically the subclasses as they are now, and could probably inherit the default notepad state.

**Comment by SadieDragon** [comment]
This is no longer an issue by design of release 0.2, and is resolved. Thank you, though.
